In [2]:
import pandas as pd

In [21]:
# 1. 读取 CSV 文件
df = pd.read_csv("output/wenchuang_ngram_stats/token_stats.csv")
df.sort_values(by="query_ratio_0_in_0_1", ascending=False, inplace=True)
df["query_ratio_0_in_0_2"] = df.apply(lambda row: row["query_count_0"] / (1+ row["query_count_0"] + row["query_count_2"]),axis=1)
df["length"] = df.apply(lambda row: len(row["token"]),axis=1)
df = df[(df["query_count_0"] > 10) & (df["length"] > 1) & (df["query_ratio_0_in_0_1"] > 0.5) & (df["query_ratio_0_in_0_2"] > 0.8)]
bad_tokens = df['token'].tolist()
df.head(20)

,token,tokens,pos,n,query_count_0,query_count_1,query_count_2,query_count_0_1,query_ratio_0_in_0_1,query_ratio_1_in_0_1,occurrence_count_0,occurrence_count_1,occurrence_count_2,occurrence_count_0_1,occurrence_ratio_0_in_0_1,occurrence_ratio_1_in_0_1,query_ratio_0_in_0_2,length
1907,一键,一键,"['n', '修饰词', '生活用语类']",1,12,0,0,12,1.000000,0.000000,12,0,0,12,1.000000,0.000000,0.923077,2
2059,主要职责,主要职责,"['l', '个体描述', '生活用语类']",1,11,0,0,11,1.000000,0.000000,11,0,0,11,1.000000,0.000000,0.916667,4
13,ppt,ppt,"['eng', '作品', '作品类_实体']",1,826,2,0,828,0.997585,0.002415,826,2,0,828,0.997585,0.002415,0.998791,3
62,导图,导图,"['n', '生活用语', '生活用语类']",1,351,1,0,352,0.997159,0.002841,351,1,0,352,0.997159,0.002841,0.997159,2
148,表格,表格,"['n', '文件', '文化类_制度政策协议']",1,176,2,0,178,0.988764,0.011236,176,2,0,178,0.988764,0.011236,0.994350,2
101,课件,课件,"['n', '生活用语', '生活用语类']",1,228,4,0,232,0.982759,0.017241,231,4,0,235,0.982979,0.017021,0.995633,2
56,思维,思维,"['n', '思想观念', '生活用语类']",1,363,8,0,371,0.978437,0.021563,364,8,0,372,0.978495,0.021505,0.997253,2
886,流程图,流程图,"['n', '生活用语', '生活用语类']",1,29,1,0,30,0.966667,0.033333,29,1,0,30,0.966667,0.033333,0.966667,3
98,好评,好评,"['v', '生活用语', '生活用语类']",1,229,9,0,238,0.962185,0.037815,231,9,0,240,0.962500,0.037500,0.995652,2
114,职责,职责,"['n', '个体描述', '生活用语类']",1,209,9,0,218,0.958716,0.041284,210,9,0,219,0.958904,0.041096,0.995238,2
1053,图片,图片,"['n', '生活用语', '生活用语类']",1,23,2,0,25,0.920000,0.080000,23,2,0,25,0.920000,0.080000,0.958333,2
1904,pdf,pdf,"['eng', '术语', '术语类']",1,11,1,0,12,0.916667,0.083333,11,1,0,12,0.916667,0.083333,0.916667,3
571,摘抄,摘抄,"['v', '生活用语', '生活用语类']",1,42,4,0,46,0.913043,0.086957,42,4,0,46,0.913043,0.086957,0.976744,2
675,第四,第四,"['m', '数量词', '生活用语类']",1,35,4,0,39,0.897436,0.102564,35,4,0,39,0.897436,0.102564,0.972222,2
206,岗位职责,岗位职责,"['n', '个体描述', '生活用语类']",1,119,14,0,133,0.894737,0.105263,119,14,0,133,0.894737,0.105263,0.991667,4
945,名人,名人,"['n', '称呼', '人物类_概念']",1,25,3,0,28,0.892857,0.107143,25,3,0,28,0.892857,0.107143,0.961538,2
570,复制,复制,"['v', '作品', '作品类_实体']",1,41,5,0,46,0.891304,0.108696,41,5,0,46,0.891304,0.108696,0.976190,2
1567,黑板报,黑板报,"['n', '作品', '作品类_实体']",1,14,2,0,16,0.875000,0.125000,14,2,0,16,0.875000,0.125000,0.933333,3
302,加油,加油,"['v', '态度', '生活用语类']",1,79,13,0,92,0.858696,0.141304,79,15,0,94,0.840426,0.159574,0.987500,2
986,忠告,忠告,"['n', '作品', '作品类_实体']",1,23,4,0,27,0.851852,0.148148,23,4,0,27,0.851852,0.148148,0.958333,2

In [26]:
result_keys = df.groupby("pos")["token"].agg(list)
key_word_result = []
for collumn in result_keys.keys():
    res = result_keys[collumn]
    print(collumn, res)
    key_word_result += res
print(key_word_result)

# keyword 进行扩招

['a', '作品', '作品类_实体'] ['成功', '重要']
['a', '数量词', '生活用语类'] ['一般']
['ad', '生活用语', '生活用语类'] ['详细']
['b', '作品', '作品类_实体'] ['主要']
['b', '教育用语', '术语类_教育用语'] ['五年级', '六年级', '七年级', '四年级', '八年级', '三年级', '二年级']
['b', '时间', '时间类'] ['年级', '高一']
['c', '作品', '作品类_实体'] ['还是', '可以']
['d', '作品', '作品类_实体'] ['真实']
['d', '生活用语', '生活用语类'] ['好处']
['eng', '作品', '作品类_实体'] ['ppt']
['eng', '术语', '术语类'] ['pdf']
['eng', '软件类型', '作品类_概念'] ['word']
['f', '初级中学', '组织机构类_教育组织机构'] ['初中']
['j', '大夫', '人物类_概念'] ['中医']
['j', '师范大学', '组织机构类_教育组织机构'] ['北师大']
['j', '数量词', '生活用语类'] ['十大']
['j', '生活用语', '生活用语类'] ['综评']
['l', '个体描述', '生活用语类'] ['主要职责']
['m', '数量词', '生活用语类'] ['第四', '七下', '第三', '多少', '美篇', '15', '30', '第二', '三个', '第一', '一名', '60']
['n', '个体描述', '生活用语类'] ['职责', '岗位职责', '义务']
['n', '书法类型', '作品类_概念'] ['书法']
['n', '事件', '事件类'] ['事例', '事件']
['n', '人员', '人物类_概念'] ['专员']
['n', '企业', '组织机构类_企事业单位'] ['集团']
['n', '作品', '作品类_实体'] ['黑板报', '忠告', '小报', '作品', '环境']
['n', '修饰词', '生活用语类'] ['一键', '励志', '物流', '经典']
['n', '办公室', '组织机构类_企事业单位'] ['办公室']
['n', '动物', '生物类_动物'] ['动物']
['n', '医学术语', '术语类_医药学术语'] ['用药']
['n', '商场', '场所类'] ['商场']
['n', '图书类型', '作品类_概念'] ['书籍', '绘本']
['n', '大赛', '文化类_奖项赛事活动'] ['大赛']
['n', '奖项', '文化类_奖项赛事活动'] ['一等奖']
['n', '工厂', '组织机构类_企事业单位'] ['工厂']
['n', '工艺', '术语类'] ['工艺流程']
['n', '广告', '生活用语类'] ['广告']
['n', '思想观念', '生活用语类'] ['思维', '目的']
['n', '指标', '术语类_符号指标类'] ['指标']
['n', '教育', '术语类_教育用语'] ['习作']
['n', '教育用语', '术语类_教育用语'] ['句子']
['n', '文件', '文化类_制度政策协议'] ['表格']
['n', '文化类型', '文化类'] ['板书']
['n', '文学类型', '作品类_概念'] ['故事']
['n', '文章类型', '作品类_概念'] ['文案', '读书笔记', '原文', '例文', '课文', '作文']
['n', '方法', '生活用语类'] ['步骤', '话术', '方法']
['n', '时间', '时间类'] ['下学期']
['n', '术语', '术语类'] ['单元', '科技', '数学', '物理', '语文', '生态']
['n', '标准', '文化类_制度政策协议'] ['标准']
['n', '汽车', '物体类_车辆'] ['新能源']
['n', '版本', '生活用语类'] ['人教版']
['n', '现象', '生活用语类'] ['场景']
['n', '生活用语', '生活用语类'] ['导图', '课件', '流程图', '图片', '寄语', '朋友圈', '短信', '口碑', '流程', '典型', '例子', '案例', '程序', '评论', '布置', '重要性', '知识点', '意义', '背景', '标题', '视频', '素材', '评价', '内容', '方式', '话语', '感言', '特色', '要点', '核心', '图形', '标语', '板书设计', '整理', '现场', '成就', '注意事项', '技巧', '封面']
['n', '生物', '生物类'] ['生物']
['n', '称呼', '人物类_概念'] ['名人', '店长', '中学生', '客服', '业主', '负责人', '运动员', '人物', '员工', '安全员', '人民', '客户', '小朋友', '用户', '主管', '管理员', '老板', '患者']
['n', '经理', '人物类_概念'] ['经理']
['n', '诗歌类型', '作品类_概念'] ['古诗']
['n', '运动会', '文化类_奖项赛事活动'] ['运动会']
['n', '酒店', '场所类_住宿场所'] ['酒店']
['nr', '作品', '作品类_实体'] ['温馨']
['nr', '时间', '时间类'] ['高三']
['nr', '生活用语', '生活用语类'] ['宣传语', '陈述']
['nr', '称呼', '人物类_概念'] ['高中生', '顾客', '小学生', '初中生']
['ns', '地区', '世界地区类'] ['上海']
['ns', '称呼', '人物类_概念'] ['英雄']
['ns', '等级', '术语类_符号指标类'] ['满意度']
['ns', '考试', '术语类_教育用语'] ['中考']
['r', '作品', '作品类_实体'] ['什么', '我们', '如何']
['r', '数量词', '生活用语类'] ['哪些']
['s', '高级中学', '组织机构类_教育组织机构'] ['高中']
['t', '年份', '时间类'] ['周年']
['t', '时间', '时间类'] ['初一', '初二', '九年', '初三']
['v', '个体描述', '生活用语类'] ['感受']
['v', '作品', '作品类_实体'] ['复制', '外卖', '吸引', '准备', '注意', '邀请', '分享', '辞职', '上班', '思考']
['v', '修饰词', '生活用语类'] ['通用']
['v', '态度', '生活用语类'] ['加油', '感谢']
['v', '教育', '术语类_教育用语'] ['宣教', '写作']
['v', '教育用语', '术语类_教育用语'] ['预习']
['v', '数量词', '生活用语类'] ['下册', '上册']
['v', '术语', '术语类'] ['下载', '打卡', '统计']
['v', '生活用语', '生活用语类'] ['好评', '摘抄', '详解', '实录', '答辩', '包括', '讲课', '展示', '操作', '适合', '作用', '提高', '赠言', '离职', '描写', '做好', '提示', '探讨', '测评', '归纳', '讲解', '知识', '要求']
['v', '称呼', '人物类_概念'] ['巡检']
['v', '考试', '术语类_教育用语'] ['高考']
['vn', '作品', '作品类_实体'] ['创作', '影响']
['vn', '作品类型', '作品类_概念'] ['微信']
['vn', '旅游', '生活用语类'] ['旅游']
['vn', '生活用语', '生活用语类'] ['免费']
['z', '数量词', '生活用语类'] ['哪些方面']
['成功', '重要', '一般', '详细', '主要', '五年级', '六年级', '七年级', '四年级', '八年级', '三年级', '二年级', '年级', '高一', '还是', '可以', '真实', '好处', 'ppt', 'pdf', 'word', '初中', '中医', '北师大', '十大', '综评', '主要职责', '第四', '七下', '第三', '多少', '美篇', '15', '30', '第二', '三个', '第一', '一名', '60', '职责', '岗位职责', '义务', '书法', '事例', '事件', '专员', '集团', '黑板报', '忠告', '小报', '作品', '环境', '一键', '励志', '物流', '经典', '办公室', '动物', '用药', '商场', '书籍', '绘本', '大赛', '一等奖', '工厂', '工艺流程', '广告', '思维', '目的', '指标', '习作', '句子', '表格', '板书', '故事', '文案', '读书笔记', '原文', '例文', '课文', '作文', '步骤', '话术', '方法', '下学期', '单元', '科技', '数学', '物理', '语文', '生态', '标准', '新能源', '人教版', '场景', '导图', '课件', '流程图', '图片', '寄语', '朋友圈', '短信', '口碑', '流程', '典型', '例子', '案例', '程序', '评论', '布置', '重要性', '知识点', '意义', '背景', '标题', '视频', '素材', '评价', '内容', '方式', '话语', '感言', '特色', '要点', '核心', '图形', '标语', '板书设计', '整理', '现场', '成就', '注意事项', '技巧', '封面', '生物', '名人', '店长', '中学生', '客服', '业主', '负责人', '运动员', '人物', '员工', '安全员', '人民', '客户', '小朋友', '用户', '主管', '管理员', '老板', '患者', '经理', '古诗', '运动会', '酒店', '温馨', '高三', '宣传语

In [5]:
## 总结规律如下：
import re
def re_judge(regexs, string):
    for pattern in regexs: #["\\d{2,4}", "[零一二三四五六七八九十百千]+首"]:
        result = re.search(pattern, string)
        if result:
            return True
    return False


def key_judge(key_word_result, string):
    for key in key_word_result:
        if key in string:
            return True
    return False

key_judge(key_word_result, "中国共党") or re_judge(["第\\d", "[一二三四五六七八九]年级|\\d年级", "第[一二三四五六七八九]|[一二三四五六七八九]名|[一二三四五六七八九]个", "[一二三四五六七八九]年级|高中生|高中学生|小学生|初中生", "初[一二三四五六七八九]"], "3年级")

True

In [13]:
import json
import requests

text = "苹果"

# 配置：启用细粒度NER
obj = {
    "str": text,
    "options": {
        "input_spec": {"lang": "chs"},     # chs=中文, en=英文, auto=自动
        "ner": {
            "enable": True,                # 启用实体识别
            "fine_grained": True           # 关键：启用细粒度识别！
        }
    }
}
!export https_proxy=http://agent.baidu.com:8891
!export http_proxy=http://agent.baidu.com:8891
req_str = json.dumps(obj).encode()
url = "https://texsmart.qq.com/api"
r = requests.post(url, data=req_str)
r.encoding = "utf-8"

result = json.loads(r.text)

# 输出识别到的实体
for entity in result.get("entity_list", []):
    print(f"实体: {entity['str']}")
    print(f"类型: {entity['type']['i18n']}")      # 中文类型名，如"水果"
    print(f"类型代码: {entity['type']['name']}")  # 如"food.fruit"
    print(f"同义词: {entity['meaning']['related']}")
    print("---")

ConnectTimeout: HTTPSConnectionPool(host='texsmart.qq.com', port=443): Max retries exceeded with url: /api (Caused by ConnectTimeoutError(<HTTPSConnection(host='texsmart.qq.com', port=443) at 0x7f694f47b7d0>, 'Connection to texsmart.qq.com timed out. (connect timeout=None)'))

In [24]:
df_ngram = pd.read_csv("output/wenchuang_ngram_stats/ngram_stats.csv")
df_ngram.sort_values(by="query_ratio_0_in_0_1", ascending=False, inplace=True)
df_ngram["query_ratio_0_in_0_2"] = df_ngram.apply(lambda row: row["query_count_0"] / (1+ row["query_count_0"] + row["query_count_2"]),axis=1)
df_ngram["length"] = df_ngram.apply(lambda row: len(row["ngram"]),axis=1)
df_ngram["1gram"] = df_ngram['tokens'].apply(lambda x: False if x in bad_tokens else True)
df_ngram = df_ngram[(df_ngram["query_count_0"] > 3) & (df_ngram["length"] > 1) & (df_ngram["query_ratio_0_in_0_1"] > 0.7) & (df_ngram["query_ratio_0_in_0_2"] > 0.8)]
df_ngram.head(50)

,ngram,tokens,pos,n,query_count_0,query_count_1,query_count_2,query_count_0_1,query_ratio_0_in_0_1,query_ratio_1_in_0_1,occurrence_count_0,occurrence_count_1,occurrence_count_2,occurrence_count_0_1,occurrence_ratio_0_in_0_1,occurrence_ratio_1_in_0_1,query_ratio_0_in_0_2,length,1gram
13,单元思维,单元/思维,"['n', '术语', '术语类']/['n', '思想观念', '生活用语类']",2,148,0,0,148,1.0,0.0,148,0,0,148,1.0,0.0,0.993289,4,True
126,的思维,的/思维,"['uj', '单字', '生活用语类']/['n', '思想观念', '生活用语类']",2,55,0,0,55,1.0,0.0,55,0,0,55,1.0,0.0,0.982143,3,True
114,的ppt,的/ppt,"['uj', '单字', '生活用语类']/['eng', '作品', '作品类_实体']",2,61,0,0,61,1.0,0.0,61,0,0,61,1.0,0.0,0.983871,4,True
112,ppt模板,ppt/模板,"['eng', '作品', '作品类_实体']/['n', '材料', '物体类']",2,61,0,0,61,1.0,0.0,61,0,0,61,1.0,0.0,0.983871,5,True
169,好评评语,好评/评语,"['v', '生活用语', '生活用语类']/['nz', '生活用语', '生活用语类']",2,43,0,0,43,1.0,0.0,43,0,0,43,1.0,0.0,0.977273,4,True
162,表格模板,表格/模板,"['n', '文件', '文化类_制度政策协议']/['n', '材料', '物体类']",2,45,0,0,45,1.0,0.0,45,0,0,45,1.0,0.0,0.978261,4,True
211,的职责,的/职责,"['uj', '单字', '生活用语类']/['n', '个体描述', '生活用语类']",2,37,0,0,37,1.0,0.0,37,0,0,37,1.0,0.0,0.973684,3,True
195,课件ppt,课件/ppt,"['n', '生活用语', '生活用语类']/['eng', '作品', '作品类_实体']",2,39,0,0,39,1.0,0.0,39,0,0,39,1.0,0.0,0.975000,5,True
394,职责和,职责/和,"['n', '个体描述', '生活用语类']/['c', '单字', '生活用语类']",2,24,0,0,24,1.0,0.0,24,0,0,24,1.0,0.0,0.960000,3,True
503,护理ppt,护理/ppt,"['n', '医学术语', '术语类_医药学术语']/['eng', '作品', '作品类_...",2,19,0,0,19,1.0,0.0,19,0,0,19,1.0,0.0,0.950000,5,True
575,好评50,好评/50,"['v', '生活用语', '生活用语类']/['m', '数量词', '生活用语类']",2,17,0,0,17,1.0,0.0,17,0,0,17,1.0,0.0,0.944444,4,True
548,班会ppt,班会/ppt,"['n', '会议', '文化类_奖项赛事活动']/['eng', '作品', '作品类_实体']",2,18,0,0,18,1.0,0.0,18,0,0,18,1.0,0.0,0.947368,5,True
599,下册第四,下册/第四,"['v', '数量词', '生活用语类']/['m', '数量词', '生活用语类']",2,16,0,0,16,1.0,0.0,16,0,0,16,1.0,0.0,0.941176,4,True
626,数学第三,数学/第三,"['n', '术语', '术语类']/['m', '数量词', '生活用语类']",2,16,0,0,16,1.0,0.0,16,0,0,16,1.0,0.0,0.941176,4,True
671,和职责,和/职责,"['c', '单字', '生活用语类']/['n', '个体描述', '生活用语类']",2,15,0,0,15,1.0,0.0,15,0,0,15,1.0,0.0,0.937500,3,True
690,数学第,数学/第,"['n', '术语', '术语类']/['m', '单字', '生活用语类']",2,15,0,0,15,1.0,0.0,15,0,0,15,1.0,0.0,0.937500,3,True
673,字好评,字/好评,"['n', '单字', '生活用语类']/['v', '生活用语', '生活用语类']",2,15,0,0,15,1.0,0.0,15,0,0,15,1.0,0.0,0.937500,3,True
789,ppt免费,ppt/免费,"['eng', '作品', '作品类_实体']/['vn', '生活用语', '生活用语类']",2,13,0,0,13,1.0,0.0,13,0,0,13,1.0,0.0,0.928571,5,True
875,10大,10/大,"['m', '数量词', '生活用语类']/['a', '单字', '生活用语类']",2,12,0,0,12,1.0,0.0,12,0,0,12,1.0,0.0,0.923077,3,True
882,一键复制,一键/复制,"['n', '修饰词', '生活用语类']/['v', '作品', '作品类_实体']",2,12,0,0,12,1.0,0.0,12,0,0,12,1.0,0.0,0.923077,4,True
906,培训ppt,培训/ppt,"['vn', '培训服务', '术语类_教育用语']/['eng', '作品', '作品类_...",2,12,0,0,12,1.0,0.0,12,0,0,12,1.0,0.0,0.923077,5,True
928,报告ppt,报告/ppt,"['n', '报告', '文化类_制度政策协议']/['eng', '作品', '作品类_实体']",2,12,0,0,12,1.0,0.0,12,0,0,12,1.0,0.0,0.923077,5,True
952,答辩ppt,答辩/ppt,"['v', '生活用语', '生活用语类']/['eng', '作品', '作品类_实体']",2,12,0,0,12,1.0,0.0,12,0,0,12,1.0,0.0,0.923077,5,True
1023,应用案例,应用/案例,"['v', '作品', '作品类_实体']/['n', '生活用语', '生活用语类']",2,11,0,0,11,1.0,0.0,11,0,0,11,1.0,0.0,0.916667,4,True
1011,大忠告,大/忠告,"['a', '单字', '生活用语类']/['n', '作品', '作品类_实体']",2,11,0,0,11,1.0,0.0,11,0,0,11,1.0,0.0,0.916667,3,True
1013,字一键,字/一键,"['n', '单字', '生活用语类']/['n', '修饰词', '生活用语类']",2,11,0,0,11,1.0,0.0,11,0,0,11,1.0,0.0,0.916667,3,True
1055,生物离职,生物/离职,"['n', '生物', '生物类']/['v', '生活用语', '生活用语类']",2,11,0,0,11,1.0,0.0,11,0,0,11,1.0,0.0,0.916667,4,True
1079,绘本ppt,绘本/ppt,"['n', '图书类型', '作品类_概念']/['eng', '作品', '作品类_实体']",2,11,0,0,11,1.0,0.0,11,0,0,11,1.0,0.0,0.916667,5,True
1117,优秀课件,优秀/课件,"['a', '作品', '作品类_实体']/['n', '生活用语', '生活用语类']",2,10,0,0,10,1.0,0.0,10,0,0,10,1.0,0.0,0.909091,4,True
1092,酒店好评,酒店/好评,"['n', '酒店', '场所类_住宿场所']/['v', '生活用语', '生活用语类']",2,11,0,0,11,1.0,0.0,11,0,0,11,1.0,0.0,0.916667,4,True
1144,培训课件,培训/课件,"['vn', '培训服务', '术语类_教育用语']/['n', '生活用语', '生活用语类']",2,10,0,0,10,1.0,0.0,10,0,0,10,1.0,0.0,0.909091,4,True
1125,内容是,内容/是,"['n', '生活用语', '生活用语类']/['v', '单字', '生活用语类']",2,10,0,0,10,1.0,0.0,10,0,0,10,1.0,0.0,0.909091,3,True
1137,口碑与,口碑/与,"['n', '生活用语', '生活用语类']/['p', '单字', '生活用语类']",2,10,0,0,10,1.0,0.0,10,0,0,10,1.0,0.0,0.909091,3,True
1191,教育ppt,教育/ppt,"['vn', '教育', '术语类_教育用语']/['eng', '作品', '作品类_实体']",2,10,0,0,10,1.0,0.0,10,0,0,10,1.0,0.0,0.909091,5,True
1240,职责及,职责/及,"['n', '个体描述', '生活用语类']/['c', '单字', '生活用语类']",2,10,0,0,10,1.0,0.0,10,0,0,10,1.0,0.0,0.909091,3,True
1270,下册三,下册/三,"['v', '数量词', '生活用语类']/['m', '数量词', '生活用语类']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,3,True
1252,课思维,课/思维,"['n', '单字', '生活用语类']/['n', '思想观念', '生活用语类']",2,10,0,0,10,1.0,0.0,10,0,0,10,1.0,0.0,0.909091,3,True
1307,单元数学,单元/数学,"['n', '术语', '术语类']/['n', '术语', '术语类']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,4,True
1318,好评100,好评/100,"['v', '生活用语', '生活用语类']/['m', '数量词', '生活用语类']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,5,True
1321,字复制,字/复制,"['n', '单字', '生活用语类']/['v', '作品', '作品类_实体']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,3,True
1328,导图简单,导图/简单,"['n', '生活用语', '生活用语类']/['a', '作品', '作品类_实体']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,4,True
1354,施工流程,施工/流程,"['vn', '生活用语', '生活用语类']/['n', '生活用语', '生活用语类']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,4,True
1360,查房ppt,查房/ppt,"['v', '生活用语', '生活用语类']/['eng', '作品', '作品类_实体']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,5,True
1351,教学课件,教学/课件,"['n', '教育用语', '术语类_教育用语']/['n', '生活用语', '生活用语类']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,4,True
1420,记录表格,记录/表格,"['n', '生活用语', '生活用语类']/['n', '文件', '文化类_制度政策协议']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,4,True
1411,职责是,职责/是,"['n', '个体描述', '生活用语类']/['v', '单字', '生活用语类']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,3,True
1416,表格怎么,表格/怎么,"['n', '文件', '文化类_制度政策协议']/['r', '作品', '作品类_实体']",2,9,0,0,9,1.0,0.0,9,0,0,9,1.0,0.0,0.900000,4,True
1488,分享ppt,分享/ppt,"['v', '作品', '作品类_实体']/['eng', '作品', '作品类_实体']",2,8,0,0,8,1.0,0.0,8,0,0,8,1.0,0.0,0.888889,5,True
1595,的主要职责,的/主要职责,"['uj', '单字', '生活用语类']/['l', '个体描述', '生活用语类']",2,8,0,0,8,1.0,0.0,8,0,0,8,1.0,0.0,0.888889,5,True
1582,汇报ppt,汇报/ppt,"['nz', '报告', '文化类_制度政策协议']/['eng', '作品', '作品类_...",2,8,0,0,8,1.0,0.0,8,0,0,8,1.0,0.0,0.888889,5,True

In [31]:
result_keys = df_ngram.groupby("pos")["ngram"].agg(list)
word_ngram_key_result = []
for collumn in result_keys.keys():
    res = result_keys[collumn]
    res = [r for r in res if not(key_judge(key_word_result, r) or re_judge(["第\\d", "[一二三四五六七八九]年级|\\d年级", "第[一二三四五六七八九]|[一二三四五六七八九]名|[一二三四五六七八九]个", "[一二三四五六七八九]年级|高中生|高中学生|小学生|初中生", "初[一二三四五六七八九]"], r))]
    if len(res) == 0:
        continue
    print(collumn, res)
    word_ngram_key_result += res
print(word_ngram_key_result)

['a', '作品', '作品类_实体']/['d', '单字', '生活用语类']/['a', '作品', '作品类_实体'] ['简单又漂亮']
['a', '单字', '生活用语类']/['r', '作品', '作品类_实体'] ['好怎么']
['a', '生活用语', '生活用语类']/['vn', '作品', '作品类_实体'] ['具体工作']
['b', '修饰词', '生活用语类']/['v', '单字', '生活用语类'] ['高级感']
['c', '单字', '生活用语类']/['n', '作品', '作品类_实体'] ['和历史']
['c', '单字', '生活用语类']/['v', '作品', '作品类_实体'] ['和反馈']
['c', '单字', '生活用语类']/['vn', '作品', '作品类_实体'] ['和工作', '及工作']
['d', '单字', '生活用语类']/['a', '作品', '作品类_实体'] ['又漂亮']
['d', '单字', '生活用语类']/['v', '单字', '生活用语类'] ['单招']
['m', '数量词', '生活用语类']/['a', '单字', '生活用语类'] ['10大']
['m', '数量词', '生活用语类']/['b', '版本', '生活用语类'] ['2023最新版']
['m', '数量词', '生活用语类']/['m', '单字', '生活用语类'] ['800米']
['m', '数量词', '生活用语类']/['m', '数量词', '生活用语类'] ['10个']
['m', '数量词', '生活用语类']/['n', '单字', '生活用语类'] ['三十字', '12课', '11课']
['m', '数量词', '生活用语类']/['n', '单字', '生活用语类']/['v', '单字', '生活用语类'] ['50字可']
['m', '数量词', '生活用语类']/['n', '数量词', '生活用语类'] ['个方面']
['m', '数量词', '生活用语类']/['v', '单字', '生活用语类'] ['100例']
['n', '作品', '作品类_实体']/['m', '单字', '生活用语类'] ['历史第']
['n', '作品', '作品类_实体']/['p', '单字', '生活用语类'] ['历史对']
['n', '关系', '生活用语类']/['uj', '单字', '生活用语类'] ['关系的']
['n', '单位', '术语类_符号指标类']/['r', '作品', '作品类_实体'] ['单位怎么']
['n', '姓氏', '人物类_概念']/['vn', '作品', '作品类_实体'] ['姓氏研究']
['n', '姓氏', '人物类_概念']/['vn', '作品', '作品类_实体']/['n', '报告', '文化类_制度政策协议'] ['姓氏研究报告']
['n', '措施', '生活用语类']/['v', '单字', '生活用语类'] ['措施有']
['n', '生活用语', '生活用语类']/['c', '单字', '生活用语类'] ['原因和']
['n', '生活用语', '生活用语类']/['n', '单字', '生活用语类'] ['入场词']
['n', '生活用语', '生活用语类']/['p', '单字', '生活用语类'] ['原因与', '经历与']
['n', '生活用语', '生活用语类']/['v', '单字', '生活用语类'] ['主题有']
['n', '生活用语', '生活用语类']/['v', '生活用语', '生活用语类'] ['账务处理']
['n', '生活用语', '生活用语类']/['vn', '作品', '作品类_实体'] ['岗位工作', '重点工作']
['n', '称呼', '人物类_概念']/['p', '单字', '生活用语类'] ['爷爷对']
['n', '称呼', '人物类_概念']/['uj', '单字', '生活用语类'] ['服务员的', '文员的', '教授的']
['n', '称呼', '人物类_概念']/['uj', '单字', '生活用语类']/['n', '术语', '术语类'] ['教授的学术']
['n', '称呼', '人物类_概念']/['v', '作品', '作品类_实体'] ['儿子结婚']
['n', '称呼', '人物类_概念']/['vn', '修饰词', '生活用语类'] ['学生综合']
['n', '称呼', '人物类_概念']/['vn', '修饰词', '生活用语类']/['n', '个体描述', '生活用语类'] ['学生综合素质']
['n', '质量', '术语类_符号指标类']/['uj', '单字', '生活用语类'] ['质量的']
['ng', '单字', '生活用语类']/['m', '数量词', '生活用语类'] ['稿50', '稿100']
['ng', '单字', '生活用语类']/['m', '数量词', '生活用语类']/['n', '单字', '生活用语类'] ['稿50字']
['ng', '单字', '生活用语类']/['uj', '单字', '生活用语类'] ['时的']
['nr', '单字', '生活用语类']/['n', '称呼', '人物类_概念'] ['毛爷爷']
['nr', '单字', '生活用语类']/['n', '称呼', '人物类_概念']/['p', '单字', '生活用语类'] ['毛爷爷对']
['nr', '幼儿园', '组织机构类_教育组织机构']/['n', '课程', '术语类_教育用语'] ['幼儿园课程']
['nz', '语言', '文化类_语言文字']/['m', '单字', '生活用语类'] ['英语第']
['nz', '颜色', '生活用语类']/['n', '教育用语', '术语类_教育用语'] ['七彩课堂']
['r', '作品', '作品类_实体']/['v', '单字', '生活用语类'] ['怎样做', '怎么发', '怎么做']
['r', '作品', '作品类_实体']/['v', '生活用语', '生活用语类'] ['怎么表述']
['r', '角色', '其他角色类']/['uj', '单字', '生活用语类'] ['别人的']
['uj', '单字', '生活用语类']/['m', '数量词', '生活用语类'] ['的10']
['uj', '单字', '生活用语类']/['m', '数量词', '生活用语类']/['a', '单字', '生活用语类'] ['的10大']
['uj', '单字', '生活用语类']/['m', '数量词', '生活用语类']/['m', '数量词', '生活用语类'] ['的10个']
['uj', '单字', '生活用语类']/['n', '作品', '作品类_实体'] ['的目标']
['uj', '单字', '生活用语类']/['n', '术语', '术语类'] ['的学术']
['uj', '单字', '生活用语类']/['n', '生活用语', '生活用语类'] ['的主题']
['uj', '单字', '生活用语类']/['n', '生活用语', '生活用语类']/['r', '作品', '作品类_实体'] ['的结尾怎么']
['uj', '单字', '生活用语类']/['n', '生活用语', '生活用语类']/['r', '作品', '作品类_实体']/['v', '单字', '生活用语类'] ['的结尾怎么写']
['uj', '单字', '生活用语类']/['n', '能力', '生活用语类'] ['的能力']
['uj', '单字', '生活用语类']/['ns', '态度', '生活用语类'] ['的赞美']
['uj', '单字', '生活用语类']/['v', '生活用语', '生活用语类'] ['的任职']
['uj', '单字', '生活用语类']/['v', '生活用语', '生活用语类']/['n', '生活用语', '生活用语类'] ['的任职经历']
['uj', '单字', '生活用语类']/['v', '生活用语', '生活用语类']/['n', '生活用语', '生活用语类']/['p', '单字', '生活用语类'] ['的任职经历与']
['uj', '单字', '生活用语类']/['vn', '作品', '作品类_实体'] ['的工作']
['uj', '单字', '生活用语类']/['vn', '服务', '生活用语类'] ['的服务']
['v', '单字', '生活用语类']/['n', '单字', '生活用语类'] ['说课']
['v', '态度', '生活用语类']/['n', '作品', '作品类_实体'] ['激励计划']
['v', '时间', '时间类']/['f', '单字', '生活用语类'] ['结束后']
['v', '生活用语', '生活用语类']/['n', '生活用语', '生活用语类'] ['任职经历']
['v', '生活用语', '生活用语类']/['n', '生活用语', '生活用语类']/['p', '单字', '生活用语类'] ['任职经历与']
['v', '生活用语', '生活用语类']/['uj', '单字', '生活用语类'] ['验收的']
['vn', '作品', '作品类_实体']/['n', '材料', '物体类'] ['设计模板']
['vn', '作品', '作品类_实体']/['r', '作品', '作品类_实体'] ['工作怎么']
['vn', '称呼', '人物类_概念']/['vn', '作品', '作品类_实体'] ['监理工作']
['简单又漂亮', '好怎么', '具体工作', '高级感', '和历史', '和反馈', '和工作', '及工作', '又漂亮', '单招', '10大', '2023最新版', '800米', '10个', '三十字', '12课', '11课', '50字可', '个方面', '100例', '历史第', '历史对', '关系的', '单位怎么', '姓氏研究', '姓氏研究报告', '措施有', '原因和', '入场词', '原因与', '经历与', '主题有', '账务处理', '岗位工作', '重点工作', '爷爷对', '服务员的', '文员的', '教授的', '教授的学术', '儿子结婚', '学生综合', '学生综合素质', '质量的', '稿50', '稿100', '稿50字', '时的', '毛爷爷', '毛爷爷对', '幼儿园课程', '英语第', '七彩课堂', '怎样做', '怎么发', '怎么做', '怎么表述', '别人的', '的10', '的10大', '的10个', '的目标', '的学术', '的主题', '的结尾怎么', '的结尾怎么写', '的能力', '的赞美', '的任职', '的任职经历', '的任职经历与', '的工作', '的服务', '说课', '激励计划', '结束后', '任职经历', '任职经历与', '验收的', '设计模板', '工作怎么', '监理工作']

### 验收 汉语数据

In [80]:
key_words = word_ngram_key_result + key_word_result
dataframe = pd.read_excel("验收数据/汉语_验收数据_0424.xlsx")
dataframe.head()
dataframe["label"] = dataframe["Query"].apply(lambda query: 1 if not(key_judge(key_word_result, query) or re_judge(["\\d{2,10}", "[零一二三四五六七八九百千]+首"], query)) else 0)
dataframe.head(20)
dataframe.to_excel("验收数据/汉语_验收数据_0424_清洗结果.xlsx")

In [11]:
result = re.search("[零一二三四五六七八九十百千]+首", "二首古诗")

In [20]:
key_words = word_ngram_key_result + key_word_result
# env_run/output/zacharychu/code/star_static/output/验收数据/汉语_511.csv
# env_run/output/zacharychu/code/star_static/output/验收数据/汉语_51378_511.csv
dataframe = pd.read_csv("output/验收数据/汉语_51387_511.csv", sep=",")
dataframe.head()
dataframe["label"] = dataframe["Query"].apply(lambda query: 1 if not(key_judge(key_word_result, query) or re_judge(["\\d{2,10}", "[零一二三四五六七八九百千]+首"], query)) else 0)
dataframe.head(20)
dataframe.to_excel("output/验收数据/汉语_51387_511_清洗结果.xlsx",index=None)

/tmp/ipykernel_134775/4076841018.py:4: DtypeWarning: Columns (0: 日期范围) have mixed types. Specify dtype option on import or set low_memory=False.
  dataframe = pd.read_csv("output/验收数据/汉语_51387_511.csv", sep=",")

In [19]:
dataframe.head()

     Query  阿拉丁资源id               日期范围  总检索次数  label
0  《现代诗》摘抄    51378  20260219~20260416  31766      1
1      长歌行    51378  20260210~20260507  25818      1
2       关雎    51378  20260227~20260430  20993      1
3        爱    51378  20260301~20260414  20105      1
4       春晓    51378  20260213~20260413  18057      1

# 验收文创

In [35]:
key_words = word_ngram_key_result + key_word_result
# env_run/output/zacharychu/code/star_static/output/验收数据/文创线上数据.xlsx
dataframe = pd.read_excel("output/验收数据/文创线上数据.xlsx")
dataframe.head()
dataframe["label"] = dataframe["Query"].apply(lambda query: 1 if not(key_judge(key_word_result, query) or re_judge(["第\\d", "[一二三四五六七八九]年级|\\d年级", "第[一二三四五六七八九]|[一二三四五六七八九]名|[一二三四五六七八九]个", "[一二三四五六七八九]年级|高中生|高中学生|小学生|初中生", "初[一二三四五六七八九]"], query)) else 0)
dataframe.head(20)
dataframe.to_excel("output/验收数据/文创线上数据_清洗数据.xlsx", index=None)